Limbs.Web/ViewModels/AmbassadorPanelViewModel.cs
using System.Collections.Generic;
using Limbs.Web.Entities.Models;

namespace Limbs.Web.ViewModels
{
    public class AmbassadorPanelViewModel
    {
        public OrderStats Stats { get; set; }
        public List<OrderModel> PendingToAssignOrders { get; set; }
        public List<OrderModel> PendingOrders { get; set; }
        public List<OrderModel> DeliveredOrders { get; set; }
    }

    public class OrderStats
    {
        public int HandledOrders { get; set; }

        public int PendingOrders { get; set; }

    }
}

Limbs.Web/Areas/Admin/Controllers/AmbassadorsController.cs
using System;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Limbs.Web.Areas.Admin.Controllers
{
    public class AmbassadorsController : AdminBaseController
    {
        // GET: Admin/Ambassadors
        public ActionResult Index()
        {
            return View(Db.AmbassadorModels.ToList());
        }

        // GET: Admin/Ambassadors/CsvExport
        public async Task<FileContentResult> CsvExport()
        {

            var dataList = await Db.AmbassadorModels.ToListAsync();
            var sb = new StringBuilder();

            var firstAmbassador = dataList.FirstOrDefault();
            var ambassadorExportTitles = firstAmbassador.GetTitles();
            sb.AppendLine(String.Join(",", ambassadorExportTitles));

            foreach (var ambassador in dataList)
            {
                string ambassadorText = ambassador.ToString();
                sb.AppendLine(ambassadorText);
            }

            var DateTimeExport = DateTime.Now.ToString("yyyyMMddHHmmss", CultureInfo.InvariantCulture);

            var nameCsv = String.Format("embajadores_{0}.csv", DateTimeExport);

            var data = Encoding.UTF8.GetBytes(sb.ToString());
            var result = Encoding.UTF8.GetPreamble().Concat(data).ToArray();

            return File(result, "text/csv", nameCsv);
                    
        }

        // GET: Admin/Ambassador/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ambassadorModel = await Db.AmbassadorModels.FindAsync(id);
            if (ambassadorModel == null)
            {
                return HttpNotFound();
            }
            return View(ambassadorModel);
        }

        // GET: Admin/Ambassador/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ambassadorModel = await Db.AmbassadorModels.FindAsync(id);
            if (ambassadorModel == null)
            {
                return HttpNotFound();
            }
            return View(ambassadorModel);
        }

        // POST: Admin/Ambassador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var ambassadorModel = await Db.AmbassadorModels.FindAsync(id);
            if (ambassadorModel == null)
            {
                return HttpNotFound();
            }

            Db.AmbassadorModels.Remove(ambassadorModel);
            await Db.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Limbs.Web/Controllers/AmbassadorController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Data.Entity.Spatial;
using System.Data.Entity.SqlServer;
using System.Data.SqlTypes;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Limbs.Web.Common.Extensions;
using Limbs.Web.Common.Geocoder;
using Limbs.Web.Common.Mail;
using Limbs.Web.Common.Mail.Entities;
using Limbs.Web.Entities.Models;
using Limbs.Web.Storage.Azure.QueueStorage;
using Limbs.Web.Storage.Azure.QueueStorage.Messages;
using Limbs.Web.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.SqlServer.Types;

namespace Limbs.Web.Controllers
{
    [DefaultAuthorize(Roles = AppRoles.Ambassador)]
    public class AmbassadorController : BaseController
    {
        private ApplicationUserManager _userManager;
        private readonly string _fromEmail = ConfigurationManager.AppSettings["Mail.From"];

        public ApplicationUserManager UserManager
        {
            get => _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            private set => _userManager = value;
        }

        // GET: /Ambassador/
        public ActionResult Index()
        {
            var currentUserId = User.Identity.GetUserId();

            IEnumerable<OrderModel> orderList = Db.OrderModels.Where(c => c.OrderAmbassador.UserId == currentUserId)
                .Include(c => c.OrderRequestor).OrderByDescending(c => c.StatusLastUpdated).ToList();

            var deliveredOrdersCount = orderList.Count(c => c.Status == OrderStatus.Delivered);
            var pendingOrdersCount = orderList.Count(c =>
                c.Status == OrderStatus.Pending || c.Status == OrderStatus.ArrangeDelivery ||
                c.Status == OrderStatus.Ready);

            var pendingAssignationOrders = orderList.Where(o => o.Status == OrderStatus.PreAssigned).ToList();
            var pendingOrders = orderList.Where(o =>
                o.Status == OrderStatus.Pending || o.Status == OrderStatus.ArrangeDelivery ||
                o.Status == OrderStatus.Ready).ToList();
            var deliveredOrders = orderList.Where(o => o.Status == OrderStatus.Delivered).ToList();

            var viewModel = new ViewModels.AmbassadorPanelViewModel
            {
                PendingToAssignOrders = pendingAssignationOrders,
                PendingOrders = pendingOrders,
                DeliveredOrders = deliveredOrders,

                Stats = new ViewModels.OrderStats
                {
                    HandledOrders = deliveredOrdersCount,
                    PendingOrders = pendingOrdersCount
                }
            };


            return View(viewModel);
        }

        // GET: Ambassador/TermsAndConditions
        [OverrideAuthorize(Roles = AppRoles.Unassigned + "," + AppRoles.Ambassador)]
        public ActionResult TermsAndConditions()
        {
            return View();
        }

        // GET: Ambassador/Create
        [OverrideAuthorize(Roles = AppRoles.Unassigned)]
        public ActionResult Create()
        {
            return View();
        }

        // GET: Ambassador/Edit
        [OverrideAuthorize(Roles = AppRoles.Ambassador + "," + AppRoles.Administrator)]
        public async Task<ActionResult> Edit(int? id)
        {
            AmbassadorModel ambassadorModel;
            var userId = User.Identity.GetUserId();
            if (!id.HasValue && User.IsInRole(AppRoles.Ambassador))
            {
                ambassadorModel = await Db.AmbassadorModels.FirstAsync(x => x.UserId == userId);
            }
            else
            {
                if (!id.HasValue) return HttpNotFound();
                ambassadorModel = await Db.AmbassadorModels.FindAsync(id);
            }

            if (ambassadorModel == null || !ambassadorModel.CanViewOrEdit(User))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Conflict);
            }

            ViewBag.ReturnUrl = Request.UrlReferrer?.AbsoluteUri;
            return View("Create", ambassadorModel);
        }

        // POST: Ambassador/Create
        [HttpPost]
        [OverrideAuthorize(Roles = AppRoles.Unassigned + "," + AppRoles.Ambassador + "," + AppRoles.Administrator)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AmbassadorModel ambassadorModel, bool? termsAndConditions)
        {
            if (!User.IsInRole(AppRoles.Administrator))
            {
                ambassadorModel.Email = User.Identity.GetUserName();
                ambassadorModel.UserId = User.Identity.GetUserId();
            }

            await ValidateData(ambassadorModel, termsAndConditions);
            ViewBag.TermsAndConditions = termsAndConditions;
            if (!ModelState.IsValid) return View("Create", ambassadorModel);

            var ambassador = await Db.AmbassadorModels.AsNoTracking()
                .FirstOrDefaultAsync(x => x.Id == ambassadorModel.Id);
            if (ambassador == null)
            {
                //CREATE
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(Db));
                await userManager.RemoveFromRoleAsync(ambassadorModel.UserId, AppRoles.Unassigned);
                await userManager.AddToRoleAsync(ambassadorModel.UserId, AppRoles.Ambassador);

                ambassadorModel.RegisteredAt = DateTime.UtcNow;

                Db.AmbassadorModels.Add(ambassadorModel);
                await Db.SaveChangesAsync();

                await SendWelcomeEmail(ambassadorModel);

                return RedirectToAction("Index");
            }

            if (!ambassadorModel.CanViewOrEdit(User)) return new HttpStatusCodeResult(HttpStatusCode.Conflict);

            if (!ambassador.CanViewOrEdit(User))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            //EDIT
            Db.Entry(ambassadorModel).State = EntityState.Modified;
            await Db.SaveChangesAsync();

            return RedirectToAction("Index", "Manage");
        }

        [HttpGet, OverrideAuthorize(Roles = AppRoles.Ambassador)]
        public async Task<ActionResult> Covid(int pag = 0)
        {
            if (pag == 1)
            {
                pag = 0;
            }
            
            var cantPerPage = Convert.ToInt32(ConfigurationManager.AppSettings["CovidCantPag"]);

            var currentUserId = User.Identity.GetUserId();
            var model = Db.COVIDEmbajadorEntregable.Where(p => p.Ambassador.UserId == currentUserId)
                .Include(p => p.Ambassador)
                .FirstOrDefault();

            if (model == null)
            {
                model = new COVIDEmbajadorEntregable
                {
                    CantEntregable = 0,
                    Ambassador = await Db.AmbassadorModels.FirstOrDefaultAsync(p => p.UserId == currentUserId),
                    TipoEntregable = 1
                };

                Db.COVIDEmbajadorEntregable.Add(model);
                await Db.SaveChangesAsync();
            }

            var vm = Mapper.Map<CovidEmbajadorEntregableViewModel>(model);

            DbGeography location = model.Ambassador.Location;

            string coordinatesPolygon = ConfigurationManager.AppSettings["CoordinatesPolygon"];
            DbGeometry polygon = DbGeometry.PolygonFromText($"POLYGON({coordinatesPolygon})", 0);
            DbGeometry pointFromAmbassador =
                DbGeometry.PointFromText($"POINT({location.Latitude ?? 0d} {location.Longitude ?? 0d})", 0);

            if (!polygon.IsValid)
            {
                polygon = MakeValid(polygon);
            }

            if (!pointFromAmbassador.IsValid)
            {
                pointFromAmbassador = MakeValid(pointFromAmbassador);
            }

            bool contains = polygon.Contains(pointFromAmbassador);

            var tmpQuery = Db.CovidOrganizationModels.GroupJoin(
                    Db.CovidOrgAmbassadorModels,
                    organizationModel => organizationModel.Id,
                    ambassador => ambassador.CovidOrgId,
                    (x, y) => new {CovidOrganizationModel = x, CovidOrgAmbassadorModels = y})
                .SelectMany(
                    x => x.CovidOrgAmbassadorModels.DefaultIfEmpty(),
                    (x, y) => new {x.CovidOrganizationModel, CovidOrgAmbassadorModels = y})
                .GroupJoin(
                    Db.COVIDEmbajadorEntregable,
                    arg => arg.CovidOrgAmbassadorModels.CovidAmbassadorId,
                    entregable => entregable.Id,
                    (x, y) => new {x.CovidOrganizationModel, COVIDEmbajadorEntregable = y})
                .SelectMany(
                    arg => arg.COVIDEmbajadorEntregable.DefaultIfEmpty(),
                    (x, y) => new {x.CovidOrganizationModel, COVIDEmbajadorEntregable = y})
                .GroupJoin(
                    Db.AmbassadorModels,
                    arg => arg.COVIDEmbajadorEntregable.Id,
                    ambassadorModel => ambassadorModel.Id,
                    (x, y) => new {x.CovidOrganizationModel, AmbassadorModels = y})
                .SelectMany(
                    arg => arg.AmbassadorModels.DefaultIfEmpty(),
                    (x, y) => new {x.CovidOrganizationModel, AmbassadorModels = y})
                .GroupBy(x => new
                {
                    x.CovidOrganizationModel.Id,
                    Location = x.CovidOrganizationModel.Location.Distance(location) ?? 0d,
                    x.CovidOrganizationModel.Featured
                });

            if (contains)
            {
                tmpQuery = tmpQuery.OrderByDescending(x => x.Key.Featured)

Limbs.Web/Views/Ambassador/AmbassadorPanel.cshtml
@using Limbs.Web.Models
@model Limbs.Web.ViewModels.AmbassadorPanelViewModel

@{
    ViewBag.Title = "Ambassador Panel";
}


    <article id="panel_embajadores" class="min_full">
        <h1>Panel de control</h1>
        <div id="estadistica_emb">
            <div>
                <p>Entregaste</p>
                <h2>@Model.Stats.HandledOrders</h2>
                <p>Manos</p>
            </div>
            <div>
                <p>Tenés</p>
                <h2>@Model.Stats.PendingOrders</h2>
                <p>Pedidos</p>
            </div>
        </div>
        <div id="paneles_embajador">
            @if (Model.PendingToAssignOrders.Count > 0)
            {
                <article class="panel_emb">
                    <h2>Pedidos entrantes:</h2>
                    <table class="tabla_emb">
                        <tr>
                            <td>Nro. de pedido</td>
                            <td>Nombre solicitante</td>
                            <td>Fecha de solicitud</td>
                        </tr>
                        @foreach (var order in Model.PendingToAssignOrders)
                        {
                            <tr onclick="location.href = '@(Url.Action("Details", "Orders", new { id = order.Id }))'">
                                <td>#@order.Id</td>
                                <td>@order.OrderRequestor.ResponsableName</td>
                                <td>@order.Date.ToString("dd/MM/yyyy")</td>
                            </tr>
                        }
                    </table>
                </article>
            }
            

            <article class="panel_emb">
                <h2>Tus pedidos:</h2>
                <table class="tabla_emb">
                    <tr>
                        <td>Nro. de pedido</td>
                        <td>Nombre solicitante</td>
                        <td>Fecha de solicitud</td>
                        <td>Estado</td>
                    </tr>
                    @foreach (var order in Model.PendingOrders)
                    {
                        <tr onclick="location.href = '@(Url.Action("Details", "Orders", new { id = order.Id }))'">
                            <td>#@order.Id</td>
                            <td>@order.OrderRequestor.ResponsableName</td>
                            <td>@order.Date.ToString("dd/MM/yyyy")</td>
                            <td>@order.Status.ToDescription()</td>
                        </tr>
                    }
                </table>
            </article>
            @if (!Model.PointIsValid)
            {
                <p>Por favor modifique su dirección ya que no es valida.</p>
            }

            @if (Model.DeliveredOrders.Count > 0)
            {
                <article id="terminadas" class="panel_emb">
                    <h2>Terminadas:</h2>
                    <table class="tabla_emb">
                        <tr>
                            <td>Nro. de pedido</td>
                            <td>Nombre solicitante</td>
                            <td>Fecha de solicitud</td>
                            <td>Estado</td>
                        </tr>
                        @foreach (var order in Model.DeliveredOrders)
                        {
                            <tr onclick="location.href = '@(Url.Action("Details", "Orders", new { id = order.Id }))'">
                                <td>#@order.Id</td>
                                <td>@order.OrderRequestor.ResponsableName</td>
                                <td>@order.Date.ToString("dd/MM/yyyy")</td>
                                <td>@order.Status.ToDescription()</td>
                            </tr>
                        }
                    </table>
                </article>
            }

        </div>
    </article>

Limbs.Web/Views/Ambassador/Covid.cshtml
@using Limbs.Web.Common.Extensions
@model  Limbs.Web.ViewModels.CovidEmbajadorEntregableViewModel

@{
    ViewBag.Title = "COVID-19";

    string headerTotal = Response.Headers.Get("X-TOTAL-PAGES");
    var totalPages = string.IsNullOrEmpty(headerTotal) ? 1 : Convert.ToInt32(headerTotal);

    string queryPage = HttpContext.Current.Request.QueryString["pag"];
    var actualPage = string.IsNullOrEmpty(queryPage) ? 1 : int.TryParse(queryPage, out int outValue) ? outValue : 1;
}

<style>
    .card.card-l > h2 {
        margin-bottom: .75em;
    }

    .form-cantidad {
        padding: .25em;
    }

    .f-campo.f-campo-cantidad {
        width: auto;
        text-align: center;
    }

    #panel_embajadores h1.covid-header {
        padding: 0;
    }

    .text-center {
        text-align: center;
    }
    
    /* GENERAL STYLES */
    
    .pagination {
        position: relative;
        display: inline-block;
        transform: translate(-50%, -50%);
        top: 50%;
        left: 50%;
        margin-top: 2em;
    }
    
    .pagination > li {
      display: inline;
    }
    
    .pagination > li > a,
    .pagination > li > span {
      position: relative;
      float: left;
      padding: 6px 12px;
      margin-left: -1px;
      line-height: 1.42857143;
      color: #4772B2;
      text-decoration: none;
      background-color: #ffffff;
      border: 1px solid #dddddd;
    }
    
    .pagination > li > a:hover,
    .pagination > li > span:hover,
    .pagination > li > a:focus,
    .pagination > li > span:focus {
      z-index: 2;
      color: #4772B2;
      background-color: #eeeeee;
      border-color: #dddddd;
    }
    
    .pagination > li:first-child > a,
    .pagination > li:first-child > span {
      margin-left: 0;
      border-top-left-radius: 4px;
      border-bottom-left-radius: 4px;
    }
    
    .pagination > li:last-child > a,
    .pagination > li:last-child > span {
      border-top-right-radius: 4px;
      border-bottom-right-radius: 4px;
    }
    
    .pagination > .active > a,
    .pagination > .active > span,
    .pagination > .active > a:hover,
    .pagination > .active > span:hover,
    .pagination > .active > a:focus,
    .pagination > .active > span:focus {
      z-index: 3;
      color: #ffffff;
      cursor: default;
      background-color: #4772B2;
      border-color: #4772B2;
    }
    
    .pagination > .disabled > span,
    .pagination > .disabled > span:hover,
    .pagination > .disabled > span:focus,
    .pagination > .disabled > a,
    .pagination > .disabled > a:hover,
    .pagination > .disabled > a:focus {
      color: #777777;
      cursor: not-allowed;
      background-color: #ffffff;
      border-color: #dddddd;
    }
</style>

<div id="loadingModal" style="display: none;">
    <div class="loader"></div>
</div>

<article id="panel_embajadores">
    <div id="Header" class="head_info">
        <h1 class="covid-header">Covid-19</h1>
    </div>
    <div id="paneles_embajador">
        <article class="card card-l">
            <h2>Cantidad de mascarillas a donar</h2>
            @using (Html.BeginForm("GuardarCantidad", "Ambassador", FormMethod.Post, new {@class = "form form-quantity"}))
            {
                @Html.HiddenFor(model => model.AmbassadorId)
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.TipoEntregable)

                <div class="f-seccion">
                    <label class="f-label">Cantidad Actual</label>
                    <div>
                        <button class="bn_blue removeCovidQuantity" type="button">
                            <i class="fa fa fa-minus"></i>
                        </button>
                        @Html.EditorFor(model => model.CantEntregable, new {htmlAttributes = new {@class = "f-campo f-campo-cantidad", @readonly = true}})
                        <button class="bn_blue addCovidQuantity" type="button">
                            <i class="fa fa fa-plus"></i>
                        </button>
                    </div>
                </div>

                <br/>
                <button class="bn_blue sendQuantity">Actualizar</button>
                <div>
                    <span class="quantityResponseMsg"></span>
                </div>
            }
        </article>
        <article class="card card-l">
            <p class="text-center">
                <img src=@Url.Content("~/Content/img/covidgif.gif") width="208">
            </p>
            <br/>
            <p>
                Hola Embajadores, por la situación actual que estamos pasando con el COVID-19, decidimos poner a disposición la plataforma Limbs para imprimir mascaras. Por favor, entra a este link: <a href="https://docs.google.com/document/d/1heHV7ln9IMKOava4vjm16t5udWLC7l42xcAc8hy6YdY" target="_blank"> MANUAL DE MASCARAS</a> para entender el funcionamiento de la plataforma.
            </p>
            <br/>
            <p>Cualquier duda escribinos en <a href="https://facebook.com/theatomiclab" target="_blank"> facebook.com/theatomiclab.</a> </p>
        </article>

    </div>
</article>

@if (Model.Orders.Count > 0)
{
    <h2 class="text-bold" style="margin: 0.75em .45em; ">Pedidos ordenados por cercanía</h2>
    <article id="info_pedido">
        <div class="grid_pedidos">
            @foreach (var order in Model.Orders)
            {
                if (order.OrderInfo != null)
                {
                    string featuredStr = order.OrderInfo.Featured ? "<strong>¡RETIRO SIN CARGO Y ENTREGA DE FILAMENTO PLA GRATIS!</strong> <a href='https://docs.google.com/document/d/14Yl0-Vf11PRqmna8KSdc-fSF7cbHaazyscUY0hw_9uw/' target='_blank'>Más info acá</a>" : string.Empty;
                    string featuredClass = order.OrderInfo.Featured ? "featured" : string.Empty;
                    <div class="card card-l @featuredClass">
                        <h2>Pedido #@order.OrgId</h2>
                        @using (Html.BeginForm("SaveQuantityToOrder", "Ambassador", FormMethod.Post))
                        {
                            <table class="tabla_datos">
                                <tr>
                                    <td>@order.OrderInfo.CovidOrganization.ToDescription() (a @order.OrderInfo.Distance.ToFriendlyDistanceString())</td>
                                    <td>
                                        @if (!string.IsNullOrEmpty(order.OrderInfo.CovidOrganizationName))
                                        {
                                            @order.OrderInfo.CovidOrganizationName
                                        }
                                    </td>
                                </tr>
                                <tr>
                                    <td>Cantidad necesaria</td>
                                    <td>@order.OrderInfo.Quantity</td>
                                </tr>
                                @if (order.OrderInfo.Ambassadors.Count > 0)
                                {
                                    <tr>
                                        <td>Embajadores que donaron: </td>
                                        <td>
                                            @foreach (var ambassador in order.OrderInfo.Ambassadors)
                                            {
                                                string fullTextName = $"{ambassador.Name} {ambassador.Lastname} x({ambassador.Quantity})";
                                                <p>@fullTextName</p>
                                            }
                                        </td>
                                    </tr>
                                }
                                <tr>
                                    <td colspan="2" class="text-bold">Sumarme</td>
                                </tr>
                                @if (order.OrderInfo.AlreadySavedQuantity)
                                {
                                    <tr>
                                        <td class="text-bold success" colspan="2">Te comprometiste con @order.OrderInfo.QuantitySaved unidades</td>
                                    </tr>
                                }
                                <tr>
                                    <td colspan="2">
                                        <table>
                                            <tr>
                                                <td colspan="2">
                                                    <button class="bn_blue removeCovidOrderQuantity" type="button">
                                                        <i class="fa fa fa-minus"></i>
                                                    </button>
                                                </td>
                                                <td colspan="2">
                                                    @{
                                                        var saveQt = order.OrderInfo.QuantitySaved ?? 0;
                                                        bool isEdit = order.OrderInfo.QuantitySaved != null;
                                                        var maxValue = Model.CantEntregable + saveQt;
                                                    }
                                                    <input class="f-campo f-campo-cantidad text-box single-line valid" data-val="true" data-val-number="The field CantEntregable must be a number." data-val-range=" " data-val-range-max="2147483647" data-val-range-min="0" data-val-required=" " name="SavedQuantity" readonly="True" type="number" value="@saveQt" aria-describedby="CantEntregable-error" aria-invalid="false">
                                                </td>
                                                <td colspan="2">
                                                    <button class="bn_blue addCovidOrderQuantity" data-max="@maxValue" type="button">
                                                        <i class="fa fa fa-plus"></i>
                                                    </button>
                                                </td>
                                                <td colspan="2">
                                                    <button class="bn_blue saveQuantityOrder" data-isFeatured="@order.OrderInfo.Featured" data-isEdit="@isEdit">Guardar</button>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                @if (!string.IsNullOrEmpty(featuredStr))
                                {
                                    <tr>
                                        <td colspan="2">@Html.Raw(featuredStr)</td>
                                    </tr>
                                }
                            </table>

                            <input type="hidden" name="OrgId" value="@order.OrgId"/>
                            <input type="hidden" name="CovidAmbassadorId" value="@Model.Id"/>
                        }
                    </div>
                }
            }
        </div>
        <div class="pag-container">
            <ul id="pagination-demo" data-totalPages="@totalPages" data-actualPage="@actualPage" class="pagination"></ul>
        </div>
    </article>
}
else
{
    <h2 class="text-bold">Aún no hay pedidos</h2>
}

@section scripts
{
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <script src="~/Scripts/jquery.twbsPagination.min.js"></script>
    <script src="~/Scripts/pages/ambassador_covid.js"></script>
}

Limbs.Web/Views/Ambassador/Delete.cshtml
@model Limbs.Web.Models.AmbassadorModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Embajadores</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.AmbassadorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmbassadorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        @*

                      --Leave comments for possible evolution-#idEvolution = 1#-----##

            <dt>
                @Html.DisplayNameFor(model => model.AtributoEmbajador1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AtributoEmbajador1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AtributoEmbajador2)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AtributoEmbajador2)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AtributoEmbajador3)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AtributoEmbajador3)
            </dd>
        *@
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>